name = input("What is your name?")
print("")
print("")
print(f"Hello {name}! Can i tell u some jokes?")
input("")
print("How do you stop a bull from charging?")
input("")
print("You cancel its credit card")
input("")
print("Can i tell u another one!")
input("")
print("")
print("What did my football coach say to the broken vending machine?")
input("")
print("Give me a quarterback!!!")
input("")
print("Can i Tell you another joke?")
print("")
input("")
print("If you said Yes great!!!")
print("If you said no to bad ur gonna hear it anyway")
input("")
print("What kind of tea is hard to swallow ")
input("")
print("REALITY")
input("")
print("I hope u liked my jokes... if u didnt ur mean... BYEEEEEEEEE")