print("")
print("")
print("")
print("U WILL DO MY MADLIB!!!")
input("")
name = input("Whats ur name????")
print(f"Hiiii {name} are u ready to madlib!")
input("")
job = input("Job:")
Msname = input("Full Name:")
skill = input(r"Skill(dont end with ing):") 
adjective= input("Adjective:")
around = input("Person or animal:")
hobby = input(r"A Hobby(dont end with ing):")
adjective2 = input("Adjective:")
Object = input("Object:")
print("Ready to hear ur storyyyyyyyyyyyyyyyyyyyyy!")
input("")
print(r"------------------------------------------------------------")
print(f"Today a {job} named {Msname} came to school to talk to us about her job.")
input("")
print(f"She said the most important skill you need to know to do her job is how to {skill} around a {adjective} {around}!")
input("")
print(f"She said it was easy for her to learn how to do her job because she loved to {hobby} when she was my age - and that helps alot!")
input("")
print(f"If your considering becoming a {job} i hope you can be near a {adjective2} {Object}.")
input("")
print("Thats very important!")
input("")
print(f"If you get distracted in that situation you wont be able to {hobby} and if you cant do that you cant be a {job}")
print(r"-------------------------------------------------------------")
print("")
print("")
print("")
print("")
print("")
print("")